language: python
python:
  - "3.13"

# This is where the travis-pro fix goes for Coveralls
env:
  global:
    - COVERALLS_SERVICE_NAME=travis-pro

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls pyyaml

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test

after_success:
  - coveralls

deploy:
  - provider: elasticbeanstalk
    # Using secure environment variables pulled from your Travis dashboard
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1" 
    app: "swe1-app"
    env: "swe1-app-env"
    bucket: "swe-app-bucket-faiz"
    on:
      branch: main